### ISSUE TITLE
Is Rigidbody supposed to be compatible with the TransformControls of Threejs

### ISSUE THREAD

**Issue by fgarrec0397** [pmndrs/react-three-rapier#102]
Maybe related to this issue #53, but I wanted to know if the `Rigidbody` component is supposed to be compatible with the ThreeJS `TransformControls`.

I'm building a game engine and react-three-rapier seems to be the best physic engine for it, but the thing is when I want to drag an item that has physic with my TransformControls implementation it seems buggy.

I tried on a vanilla react-three-fiber and it seems to be buggy as well.

Here is my dirt codesandbox that represents the issue. 
https://codesandbox.io/p/github/fgarrec0397/rapier-issue/draft/nostalgic-sammet?file=%2Fsrc%2FApp.tsx

Just drag the cube and you will see what I'm talking about.

Thanks a lot!

**Comment by hmans** [comment]
When you wrap a scene object in a rigid body, the physics engine takes over control of the scene object, so anything _else_ that wants to modify it will directly compete with it. The solution here would involve finding a way to pause the physics simulation while the transform controls are being used, and having them update _the controlling rigidbody's transform_ instead of the scene object's.

**Comment by fgarrec0397** [comment]
That's a good strategy! The problem is if the physic is paused the `setTranslation` method doesn't work right?

Maybe I'm wrong, but from the RapierJS documentation it's the only way to move a Rigidbody and the `position` attribute seems to only work on the first render

**Comment by fgarrec0397** [comment]
With the last release it fixed my problem, so I will close this issue. Thanks!
