### ISSUE TITLE
rt-rapier breaks with StrictMode enabled

### ISSUE THREAD

**Issue by hmans** [pmndrs/react-three-rapier#118]
I recently learned that the default `<StrictMode>` setup that the typical CRA and Vite templates enable by default does not automatically extend into an R3F canvas, and that you need to explicitly create a `<StrictMode>` node _inside_ `<Canvas>` to use it. I am now going through all of my own libraries as well as some others that I'm using (like this one) to find out how badly they break with strict mode enabled, and @react-three/rapier unfortunately is one of the things that do break.

**To reproduce**, just wrap everything inside the `<Canvas>` in the demo app in a `<StrictMode>` node.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1061/193441543-c998ce57-4b81-4dfe-8c83-1ae30d7b7cea.png">

**Comment by CodyJasonBennett** [comment]
Looking into this, why not eagerly create `World` here?

https://github.com/pmndrs/react-three-rapier/blob/ab28c58e5785bcf60c53c0c07394c28ce8ecbb83/packages/react-three-rapier/src/Physics.tsx#L152-L159

I also see this in other places, although this is initialized immediately in `createWorldApi` before passing in context.

**Comment by wiledal** [comment]
Good call! I'll wrap the Demos in StrictMode from now on.

There is some work to be done on `RigidBody` lifecycles. 
React 18 Strict Mode has some annoying but necessary behaviors in order to catch potential problems, especially in Development Mode where it runs all components twice, invoking effects and state-setters both times.

The safe way to ensure a single eagerly created instance is to use the `refGetter` pattern like above ☝️ @CodyJasonBennett -- I really dislike it, but what can you do.

It would be nice to create the `world` in a `useState`, but then we'd have a non-symmetrical side-effect where we have to destroy it in an unrelated `useEffect`.

I should be passing the `refGetter` to the update hooks in the `RigidBody` instead of the refs. Strict Mode is causing the component to mount multiple times, breaking the rigid body reference in the "newest" world...

Do you have suggestions on cleaner ways of handling this?

**Comment by CodyJasonBennett** [comment]
In this case, you would nullify `worldRef.current` on unmount to unsatisfy the null check, but I wanted to understand why internals were designed that way and if they work around existing problems.
