### ISSUE TITLE
All onCollision events trigger 4 times instead of 1

### ISSUE THREAD

**Issue by RodrigoHamuy** [pmndrs/react-three-rapier#322]
Apart from `onContactForce`, it seems that all the `onCollision...` events are triggering 4 times.

sandbox: https://codesandbox.io/s/rapier-event-twice-qt7b72?file=/src/App.tsx

```tsx
<RigidBody onCollisionEnter={ ( ) => console.log( `onCollisionEnter` ) } 
```

![coll](https://user-images.githubusercontent.com/2405611/221133049-40b13527-6bc9-430a-a692-41972a9f454e.gif)

**Comment by wiledal** [comment]
There was multiple issues here!

1. The RigidBody passed down it's collision event handlers to the collider, causing it to fire twice (once on the RigidBody, once on the Collider)
2. This example is using a Plane with a trimesh-collider. Since it has zero "depth" I believe Rapier interpreted the Collision as hitting "both sides" of the trimesh at once, causing it to fire twice (I think).

The first problem should be fixed in `0.14.0-rc.1`
